# Generated by Django 2.2 on 2020-04-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startupname', models.CharField(db_column='startupname', max_length=100)),
                ('productname', models.CharField(db_column='productname', max_length=100, null=True)),
                ('sentimentscore', models.DecimalField(db_column='sentimentscore', decimal_places=3, default=0, max_digits=10)),
                ('infostartupscore', models.DecimalField(db_column='infostartupscore', decimal_places=3, default=0, max_digits=10)),
                ('infoplatformscore', models.DecimalField(db_column='infoplatformscore', decimal_places=3, default=0, max_digits=10)),
                ('totalscore', models.DecimalField(db_column='totalscore', decimal_places=3, default=0, max_digits=10)),
                ('status', models.CharField(blank=True, db_column='status', max_length=40, null=True)),
                ('changeby', models.CharField(blank=True, db_column='changeby', max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'score',
                'ordering': ['startupname'],
            },
        ),
    ]
