# Generated by Django 2.2 on 2020-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surpreapp', '0002_attribute_attributescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='scorecategory',
            field=models.CharField(blank=True, db_column='scorecategory', max_length=40, null=True),
        ),
    ]
