# Generated by Django 2.2 on 2020-04-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surpreapp', '0003_score_scorecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(db_column='label', max_length=100)),
                ('value', models.IntegerField(db_column='value', default=0)),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'db_table': 'choice',
                'ordering': ['label'],
            },
        ),
    ]
