# Generated by Django 2.2 on 2020-04-22 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surpreapp', '0004_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='changetime',
            field=models.DateTimeField(db_column='changetime', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='startupname',
            field=models.CharField(db_column='startupname', max_length=100, null=True),
        ),
    ]
