# Generated by Django 2.2 on 2020-04-23 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surpreapp', '0007_auto_20200423_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='predictdate',
        ),
        migrations.AddField(
            model_name='score',
            name='calculatedate',
            field=models.DateField(db_column='calculatedate', default=datetime.date.today),
        ),
    ]
