# Generated by Django 2.2 on 2020-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surpreapp', '0008_auto_20200423_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='calculatedate',
            field=models.DateField(db_column='calculatedate', null=True),
        ),
    ]
